FROM rust:1.62.0-alpine3.15

RUN apk update && apk add musl-dev

COPY Cargo.toml /src/Cargo.toml
COPY Cargo.lock /src/Cargo.lock
COPY cli /src/cli
COPY core /src/core
COPY dashboard /src/dashboard

RUN cargo

WORKDIR /src
CMD cargo build --release
