FROM rust:latest

#RUN apk update && apk add curl libc-dev
RUN curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
RUN cargo install cargo-generate

RUN export USER=root && wasm-pack new hello-wasm
RUN cd hello-wasm && export USER=root && wasm-pack build

WORKDIR /app