name: Cargo Builder Component

on:
  workflow_call:
    inputs:
      # https://doc.rust-lang.org/nightly/rustc/platform-support.html
      target:
        required: true
        type: string

jobs:
  cargo-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build cli for linux
        run: |
          rustup target add ${{inputs.image_name}}
          cargo build --target ${{inputs.image_name}} --release
