name: Cargo Builder Component

on:
  workflow_call:
    inputs:
      # https://doc.rust-lang.org/nightly/rustc/platform-support.html
      target:
        required: true
        type: string

jobs:
  cargo-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/project-cache

      - name: Build project
        run: |
          rustup target add ${{inputs.target}}
          cargo build --target ${{inputs.target}} --release

