name: meta-secret deployment

on:
  push:
    branches:
      - main

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build cli for linux
        run: |
          rustup target add x86_64-unknown-linux-gnu
          cargo build -p meta-secret-cli --target x86_64-unknown-linux-gnu --release
          docker build -t ghcr.io/meta-secret/meta-secret-cli:latest --file Dockerfile-cli .
          docker push ghcr.io/meta-secret/meta-secret-cli:latest       
