name: meta-secret deployment

on:
  push:
    branches:
      - main

jobs:
  docker-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build meta-secret-cli binary
        run: |
          cargo clean
          cargo build --release

      # Docker
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v2

      # https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio
      - name: Login to the Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build and push meta-secret-cli docker image
        run: |
          docker build -t ghcr.io/meta-secret/meta-secret-cli:latest --file Dockerfile-cli .
          docker push ghcr.io/meta-secret/meta-secret-cli:latest
