name: "Mobile Platforms Deployment"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/mobile.yml'
      - 'mobile/core/swift-lib/**'

jobs:
  swift-lib:
    runs-on: macos-latest
    needs: [core-deploy]

    env:
      CARGO_PROFILE_RELEASE_DEBUG: 1
      CARGO_PROFILE_RELEASE_LTO: thin
      CARGO_PROFILE_RELEASE_OPT_LEVEL: s

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            mobile/core-swift-lib/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install nightly rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          target: aarch64-apple-ios
          override: true

      - name: build rust core for ios
        working-directory: mobile/core-swift-lib
        run: cargo build --release --target aarch64-apple-ios

      - run: ls -la mobile/core-swift-lib/target/aarch64-apple-ios/release/

      - name: Upload iphone app
        uses: actions/upload-artifact@v3
        with:
          name: meta-secret-core_iphone-lib
          path: mobile/core-swift-lib/target/aarch64-apple-ios/release/libmeta_secret_core_swift.a
