name: meta-secret releases

on:
  push:
    tags:
      - "cli-*.*.*"

jobs:
  cli-linux-distribution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/x86_64-unknown-linux-gnu/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build cli for linux
        working-directory: cli
        run: |
          rustup target add x86_64-unknown-linux-gnu
          cargo build --target x86_64-unknown-linux-gnu --release
          cp config.yaml ../target/x86_64-unknown-linux-gnu/release/config.yaml

      - name: Tarball For Linux Cli
        working-directory: target/x86_64-unknown-linux-gnu/release
        run: |
          tar -cvzf meta-secret-cli-x86_64-unknown-linux-gnu.tar.gz config.yaml meta-secret-cli

      - name: Upload linux tarball
        uses: actions/upload-artifact@v3
        with:
          name: cli-linux-package
          path: target/x86_64-unknown-linux-gnu/release/meta-secret-cli-x86_64-unknown-linux-gnu.tar.gz

  cli-windows-distribution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/x86_64-pc-windows-gnu
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build cli for Windows
        working-directory: cli
        run: |
          sudo apt update
          sudo apt install -y build-essential
          sudo apt install -y gcc-mingw-w64
          rustup target add x86_64-pc-windows-gnu
          cargo build --target x86_64-pc-windows-gnu --release
          cp config.yaml ../target/x86_64-pc-windows-gnu/release/config.yaml

      - name: Tarball For Windows Cli
        working-directory: target/x86_64-pc-windows-gnu/release
        run: |
          tar -cvzf meta-secret-cli-x86_64-pc-windows-gnu.tar.gz config.yaml meta-secret-cli.exe

      - name: Upload windows tarball
        uses: actions/upload-artifact@v3
        with:
          name: cli-windows-package
          path: target/x86_64-pc-windows-gnu/release/meta-secret-cli-x86_64-pc-windows-gnu.tar.gz

  cli-macos-distribution:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/release
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build cli for macOS
        working-directory: cli
        run: |
          cargo build --release
          cp config.yaml ../target/release/config.yaml

      - name: Tarball For macOS cli
        working-directory: target/release
        run: |
          tar -cvzf meta-secret-cli-x86_64-apple-darwin.tar.gz config.yaml meta-secret-cli

      - name: Upload macOS tarball
        uses: actions/upload-artifact@v3
        with:
          name: cli-macos-package
          path: target/release/meta-secret-cli-x86_64-apple-darwin.tar.gz

  publish_release:
    runs-on: ubuntu-latest
    needs: [cli-linux-distribution, cli-macos-distribution, cli-windows-distribution]
    steps:
      - name: Download linux cli build
        uses: actions/download-artifact@v3
        with:
          name: cli-linux-package

      - name: Download windows cli build
        uses: actions/download-artifact@v3
        with:
          name: cli-windows-package

      - name: Download macOS cli build
        uses: actions/download-artifact@v3
        with:
          name: cli-macos-package

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            meta-secret-cli-x86_64-unknown-linux-gnu.tar.gz
            meta-secret-cli-x86_64-pc-windows-gnu.tar.gz
            meta-secret-cli-x86_64-apple-darwin.tar.gz
