name: meta-secret releases

on:
  push:
    tags:
      - "cli-*.*.*"

jobs:
  build-cli-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build cli for linux
        working-directory: cli
        run: |
          rustup target add x86_64-unknown-linux-gnu
          cargo build --target x86_64-unknown-linux-gnu --release
          cp config.yaml ../target/release/config.yaml

      - name: Tarball For Linux Cli
        working-directory: target/release
        run: |
          tar -cvzf meta-secret-cli-x86_64-unknown-linux-gnu.tar.gz config.yaml meta-secret-cli

      - name: Build cli for Windows
        working-directory: cli
        run: |
          sudo apt update
          sudo apt install -y build-essential
          sudo apt install -y gcc-mingw-w64
          rustup target add x86_64-pc-windows-gnu
          cargo build --target x86_64-pc-windows-gnu --release
          cp config.yaml ../target/x86_64-pc-windows-gnu/release/config.yaml

      - name: Tarball For Windows Cli
        working-directory: target/x86_64-pc-windows-gnu/release
        run: |
          tar -cvzf meta-secret-cli-x86_64-pc-windows-gnu.tar.gz config.yaml meta-secret-cli.exe

      - name: Upload linux tarball
        uses: actions/upload-artifact@v3
        with:
          name: cli-linux-package
          path: target/release/meta-secret-cli-x86_64-unknown-linux-gnu.tar.gz

  publish_release:
    runs-on: ubuntu-latest
    needs: build-cli-release
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: cli-linux-package

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/meta-secret-cli-x86_64-unknown-linux-gnu.tar.gz
