name: meta-secret releases

on:
  push:
    tags:
      - "cli-*.*.*"

jobs:
  build-cli-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build cli
        working-directory: cli
        run: |
          rustup target add x86_64-unknown-linux-gnu
          cargo build --target x86_64-unknown-linux-gnu --release
          cp config.yaml ../target/release/config.yaml

      - name: Tarball Linux package
        working-directory: target/release
        run: |
          tar -cvzf meta-secret-linux.tar.gz config.yaml meta-secret-cli

      - name: Release Linux package
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/meta-secret-linux.tar.gz
