name: testing

on: pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/actions/project-cache

    - name: run unit tests
      run: cargo test
