name: Vault Server Docker Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker-cli.yml'
      - 'vault/vault-server/**'


jobs:
  vault-server-deployment:
    uses: ./.github/workflows/cargo-build-component.yml
    with:
      target: x86_64-unknown-linux-gnu

  target-dir:
    runs-on: ubuntu-latest
    needs:
      - vault-server-deployment
    steps:
      - name: show target dir
        run: |
          ls -la target/release