name: Vault Server Docker Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker-cli.yml'
      - 'vault/vault-server/**'

jobs:
  vault-server-deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/project-cache

      - name: hello world
        run: |
          ls -la
