name: web-cli deployment

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/web-cli.yml'
      - 'web-cli'

jobs:
  web-cli-wasm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: install wasm-pack
        working-directory: /tmp
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install cargo-generate
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-generate

      - name: Build wasm package
        working-directory: web-cli/wasm
        run: |
          wasm-pack build

      - name: Upload wasm package
        uses: actions/upload-artifact@v3
        with:
          name: web-cli-wasm-package
          path: web-cli/wasm/pkg

  web-cli-npm-build:
    runs-on: ubuntu-latest
    needs: [web-cli-wasm-build]

    steps:
      - uses: actions/checkout@v3

      - name: Download wasm package
        uses: actions/download-artifact@v3
        with:
          name: web-cli-wasm-package
          path: web-cli/ui/pkg

      - name: npm build
        working-directory: web-cli/ui
        run: |
          npm install
          npm run build
